;; Global WM Settings

[global/wm]
margin-bottom = 0
margin-top = 0

;; -------------------------------------------

;; File Inclusion
; include an external file, like module file, etc.

include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini
include-file = ~/.config/polybar/custom_modules.ini

;; -------------------------------------------

;; Dummy bar for i3-gaps top

;[bar/dummy]
;monitor = "eDP1"
;monitor-fallback = "HDMI1"
;bottom = false
;width = 100%
;height = 38
;background = #00000000
;modules-center = blank
;font-0 = "Tamzen:size=11;3"
;wm-name = i3

;; -------------------------------------------

;; Main Bar Settings

[bar/main]
monitor = "eDP-1"
monitor-fallback = "HDMI-1"

; Tell the Window Manager not to configure the window.
; Use this to detach the bar if your WM is locking its size/position.
;override-redirect = true

; Do not overlap in fullscreen (only when override-redirect = true)
;wm-restack = i3

; Put the bar at the bottom of the screen
bottom = false

; Prefer fixed center position for the `modules-center` block
; When false, the center position will be based on the size of the other blocks.
fixed-center = true

; Dimension defined as pixel value (e.g. 35) or percentage (e.g. 50%),
; the percentage can optionally be extended with a pixel offset like so:
; 50%:-10, this will result in a width or height of 50% minus 10 pixels
width = 100%
height = 38

; Offset defined as pixel value (e.g. 35) or percentage (e.g. 50%)
offset-x = 0
offset-y = 0

background = ${colors.dark0_hard}
foreground = ${colors.light0_soft}

; overline-size = 5
border-size = 0
border-bottom-size = 0
border-bottom-color = ${colors.dark0_hard}
border-top-size = 0
border-top-color = ${colors.dark0_hard}

border-left-size = 0
border-left-color = ${colors.dark0_hard}

border-right-size = 8
border-right-color = ${colors.dark0_hard}

padding-left = 0
padding-right = 0

module-margin-left = 0
module-margin-right = 0

; Fonts
font-0 = "Tamzen:size=11;3"
font-1 = "FontAwesome:size=9;3"
font-2 = "DejaVu Sans:size=10;3"
font-3 = "Weather Icons:size=10;5"

; Modules
separator = 
modules-left = i3 
modules-center = date
modules-right = net_indicator backlight-acpi volume battery

; Opacity value between 0.0 and 1.0 used on fade in/out
dim-value = 1.0

; Value to be used to set the WM_NAME atom
wm-name = i3 

; Locale used to localize various module data (e.g. date)
locale = 

; Tray
tray-position = right
tray-detached = false
tray-maxsize = 22
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 1
tray-scale = 1.0
tray-transparent = false

; Set a DPI values used when rendering text
; This only affects scalable fonts
dpi = 144

; Enable support for inter-process messaging
; See the Messaging wiki page for more details.
enable-ipc = true


;; -------------------------------------------

;; Info Bar Settings

[bar/info]
monitor = "eDP-1"
monitor-fallback = "HDMI-1"
override-redirect = false
bottom = true 
fixed-center = true
width = 100%
height = 38
offset-x = 0
offset-y = 0

background = ${colors.dark0_hard}
foreground = ${colors.light0_soft}

border-size = 0
border-bottom-size = 0
border-bottom-color = ${colors.dark0_hard}
border-top-size = 0
border-top-color = ${colors.dark0_hard}
border-left-size = 0
border-left-color = ${colors.dark0_hard}
border-right-size = 8
border-right-color = ${colors.dark0_hard}

padding-left = 2
padding-right = 2

module-margin-left = 0
module-margin-right = 0

; Fonts
font-0 = "Tamzen:size=11;3"
font-1 = "FontAwesome:size=9;3"
font-2 = "DejaVu Sans:size=10;3"
font-3 = "Weather Icons:size=10;5"

; Modules
separator = 
modules-left = filesystem memory cpu temperature 
modules-center = weather 
modules-right = system-usb-udev updates-pacman-aurhelper netspeed

dim-value = 1.0
wm-name = i3 
locale = 
tray-position = none
dpi = 144
enable-ipc = true


;; -------------------------------------------

;; Application Settings

[settings]
; The throttle settings lets the eventloop swallow up til X events
; if they happen within Y millisecond after first event was received.
; This is done to prevent flood of update event.
throttle-output = 5
throttle-output-for = 10

; Reload upon receiving XCB_RANDR_SCREEN_CHANGE_NOTIFY events
screenchange-reload = true
