[module/blank]
type = custom/text
content = " "

;; -------------------------------------------

[module/i3]
type = internal/i3

pin-workspaces = true
strip-wsnumbers = false
index-sort = true

enable-click = true
enable-scroll = false

wrapping-scroll = false
reverse-scroll = false

format-padding = 1

ws-icon-0 = 1;1
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5
ws-icon-5 = 6;6
ws-icon-6 = 7;7
ws-icon-7 = 8;8
ws-icon-8 = 9;9
ws-icon-9 = 10;10
ws-icon-default = 11

format = <label-state> <label-mode>
label-focused = %icon%
label-focused-foreground = ${colors.faded_yellow}
label-focused-background = ${colors.dark0_hard}

label-focused-padding = 1
label-focused-font = 1

label-unfocused = %icon%
label-unfocused-foreground = ${colors.dark0_soft}
label-unfocused-background = ${colors.dark0_hard}
label-unfocused-underline = ${colors.light0_soft}
label-unfocused-padding = 1
label-unfocused-font = 1

label-visible = %icon%
label-visible-padding = 1
label-visible-font = 1

label-mode = %index% %mode%
label-mode-padding = 1
label-mode-background = ${colors.bright_aqua}

label-urgent = %icon%
label-urgent-foreground = ${colors.bright_red}
label-urgent-background = ${colors.dark0_soft}
label-urgent-padding = 1
label-urgent-font = 1

;; -------------------------------------------

[module/date]
type = internal/date

interval = 1.0
format-padding = 1
format-font = 1

time = %a, %d %b %Y, %H:%M:%S

format =" <label> "
format-foreground = ${colors.dark0_soft}
format-suffix = " "
format-suffix-foreground = ${colors.dark0_soft}
 
label = %time%
label-foreground = ${colors.light0_hard}

;; -------------------------------------------

[module/filesystem]
type = internal/fs
interval = 25
format-padding = 1
format-font = 0
mount-0 = /
format-mounted = " [ <label-mounted> "
format-mounted-foreground = ${colors.dark0_soft}
format-mounted-suffix = "] "
format-mounted-suffix-foreground = ${colors.dark0_soft}
format-foreground = ${colors.dark0_soft}
label-mounted = " %free%"
label-mounted-foreground = ${colors.bright_blue}
format-unmounted = " [ <label-unmounted> ] "
label-unmounted = "%mountpoint% not mounted"

[module/memory]
type = internal/memory
interval = 3
format-padding = 1
format-font = 0
format = " MEM <bar-used> "
format-foreground = ${colors.bright_yellow}

bar-used-indicator =
bar-used-width = 24
bar-used-fill-foreground = ${colors.bright_yellow}
bar-used-empty-foreground = ${colors.dark0_soft}
bar-used-fill = ∣
bar-used-empty = ∣
bar-used-fill-font = 3
bar-used-empty-font = 3

[module/cpu]
type = internal/cpu
interval = 1
format-padding = 1
format-font = 0
format = " CPU <bar-load> "
format-foreground = ${colors.bright_red}

bar-load-indicator =
bar-load-width = 24
bar-load-fill-foreground = ${colors.bright_red}
bar-load-empty-foreground = ${colors.dark0_soft}
bar-load-fill = ∣
bar-load-empty = ∣
bar-load-fill-font = 3
bar-load-empty-font = 3

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 70

format = " [ <label> "
format-suffix = "] "
format-suffix-foreground = ${colors.dark0_soft}
format-foreground = ${colors.dark0_soft}
format-padding = 1
format-font = 0
format-warn = " [ <label-warn> "
format-warn-suffix = "] "
format-warn-suffix-foreground = ${colors.dark0_soft}
label =  %temperature-c%
label-foreground = ${colors.faded_green}
label-warn =  %temperature-c%
label-warn-foreground = ${colors.faded_red}

;; -------------------------------------------

[module/xbacklight]
type = internal/xbacklight

format = " LUM <bar> "
format-padding = 1
format-font = 1

bar-width = 16
bar-gradient = false
bar-indicator =
bar-indicator-foreground = ${colors.light0_soft}
bar-indicator-font = 2

bar-fill = ∣
bar-foreground-0 = ${colors.faded_yellow}
bar-fill-font = 3

bar-empty = ∣
bar-empty-foreground = ${colors.dark0_soft}
bar-empty-font = 3

[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = intel_backlight

[module/volume]
type = internal/pulseaudio

use-ui-max = false

format-volume = " VOL <bar-volume> "
format-volume-background = ${colors.dark0_hard}
format-volume-foreground = ${colors.light0_soft}
format-padding = 1
format-font = 1

format-muted = " VOL <label-muted> "
format-muted-background = ${colors.dark0_hard}
format-muted-foreground = ${colors.faded_red}
format-muted-font = 1

label-muted = "∣∣∣∣∣∣∣∣∣∣∣∣∣∣∣"
label-muted-font = 3

bar-volume-width = 16
bar-volume-gradient = false

bar-volume-indicator = 
bar-volume-indicator-foreground = ${colors.light0_soft}
bar-volume-indicator-font = 2

bar-volume-fill = ∣
bar-volume-foreground-0 = ${colors.faded_yellow}
bar-volume-fill-font = 3

bar-volume-empty = ∣
bar-volume-empty-foreground = ${colors.dark0_soft}
bar-volume-empty-font = 3
